#!/usr/bin/env python3
"""Regenerate ``src/blitz_api/types/enums.py`` from ``openapi/enum-source.json``.

The Blitz OpenAPI spec pins several request fields to large ``enum`` lists (most
notably ``industry``, with hundreds of values). Hand-maintaining those in Python
would drift from the API. Instead the value lists are vendored verbatim in
``openapi/enum-source.json`` and this script turns them into ``str``-backed
``Enum`` classes.

Usage::

    python scripts/gen_enums.py            # rewrite enums.py
    python scripts/gen_enums.py --check     # exit 1 if enums.py is out of date

CI runs ``--check`` so a stale generated file fails the build (drift guard).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "openapi" / "enum-source.json"
TARGET = ROOT / "src" / "blitz_api" / "types" / "enums.py"

HEADER = '''\
# This file is @generated by scripts/gen_enums.py from openapi/enum-source.json.
# Do not edit by hand — run `python scripts/gen_enums.py` to regenerate.
"""String enums for Blitz API request fields with a fixed set of allowed values.

Every member is a ``str``, so an enum value can be used anywhere a plain string
is accepted and serializes to its exact API value.
"""

from __future__ import annotations

from enum import Enum

__all__ = [
{all_block}]
'''


def slug(value: str) -> str:
    """Turn an enum value into a valid, upper-snake Python identifier."""
    name = re.sub(r"[^0-9A-Za-z]+", "_", value).strip("_").upper()
    if not name:
        name = "UNKNOWN"
    if name[0].isdigit():
        name = "_" + name
    return name


def member_names(values: list[str]) -> list[tuple[str, str]]:
    """Map each value to a unique member name, disambiguating collisions."""
    seen: dict[str, int] = {}
    out: list[tuple[str, str]] = []
    for value in values:
        base = slug(value)
        if base in seen:
            seen[base] += 1
            name = f"{base}_{seen[base]}"
        else:
            seen[base] = 1
            name = base
        out.append((name, value))
    return out


def render() -> str:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    enums: dict[str, list[str]] = data["enums"]

    all_block = "".join(f'    "{name}",\n' for name in enums)
    parts = [HEADER.format(all_block=all_block)]

    for class_name, values in enums.items():
        parts.append(f"\n\nclass {class_name}(str, Enum):")
        members = member_names(values)
        if not members:
            parts.append("\n    pass")
            continue
        for member, value in members:
            parts.append(f"\n    {member} = {value!r}")
        parts.append("\n")

    return "".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify enums.py is up to date instead of writing it.",
    )
    args = parser.parse_args()

    rendered = render()

    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != rendered:
            print(
                "enums.py is out of date. Run `python scripts/gen_enums.py` and commit.",
                file=sys.stderr,
            )
            return 1
        print("enums.py is up to date.")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(rendered, encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(ROOT)} ({len(rendered.splitlines())} lines).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
