#!/usr/bin/env python3
"""Regenerate ``src/blitz_api/types/enums.py`` from the Blitz OpenAPI spec.

The spec pins several request fields to large ``enum`` lists (most notably
``industry``, with hundreds of values). Hand-maintaining those in Python would
drift from the API, so this script pulls them straight from the live spec and
turns each into a ``str``-backed :class:`~enum.Enum` class.

The spec inlines each enum and repeats it across endpoints, request
content-types, and ``include``/``exclude`` sub-objects, so the same value list
shows up 6-12 times. We map each enum to a name by its owning request property
(``PROPERTY_TO_CLASS``), collapse the identical duplicate occurrences, and
de-duplicate exact-repeat values within a list. The result is cached in
``openapi/enum-source.json`` (also generated) and rendered into ``enums.py``.

Three modes::

    python scripts/gen_enums.py --fetch     # pull the live spec, rewrite the cache
                                            #   (openapi/enum-source.json) AND enums.py
    python scripts/gen_enums.py             # render enums.py from the committed cache
    python scripts/gen_enums.py --check     # exit 1 if enums.py is out of date

Only ``--fetch`` touches the network. The default render and ``--check`` read the
committed cache offline, so CI's drift guard (``gen_enums.py --check``) stays
hermetic — it never fails because the network is down or the spec changed.

Each value is emitted via ``repr`` so the exact upstream escaping (including the
double-backslash apostrophe value) round-trips byte-for-byte.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import time
from pathlib import Path
from typing import NamedTuple, TypedDict, cast

import httpx

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "openapi" / "enum-source.json"
TARGET = ROOT / "src" / "blitz_api" / "types" / "enums.py"

# Live OpenAPI spec the enums are pulled from (only ``--fetch`` reads it).
SPEC_URL = "https://api.blitz-api.ai/openapi"

FETCH_TIMEOUT_S = 15.0
FETCH_ATTEMPTS = 3

# Maps a request-body property key to its enum class name. The "owning property"
# of an enum is the nearest ancestor key that isn't a structural keyword (see
# ``STRUCTURAL``). Declared in the canonical output order so the generated cache —
# and therefore enums.py — is deterministic regardless of spec traversal order.
# ``type`` only ever appears as ``company.type``.
PROPERTY_TO_CLASS: dict[str, str] = {
    "industry": "Industry",
    "type": "CompanyType",
    "employee_range": "EmployeeRange",
    "continent": "Continent",
    "sales_region": "SalesRegion",
    "job_function": "JobFunction",
    "job_level": "JobLevel",
}

# OpenAPI/JSON-Schema keywords skipped when resolving an enum's owning property.
STRUCTURAL: frozenset[str] = frozenset(
    {
        "items",
        "include",
        "exclude",
        "properties",
        "schema",
        "content",
        "requestBody",
        "parameters",
        "get",
        "post",
        "put",
        "patch",
        "delete",
        "anyOf",
        "allOf",
        "oneOf",
        "application/json",
        "application/x-www-form-urlencoded",
        "multipart/form-data",
    }
)

_CACHE_COMMENT = (
    "Enum value lists pulled from the Blitz OpenAPI spec and de-duplicated. "
    "GENERATED by scripts/gen_enums.py --fetch — do not hand-edit; run "
    "`python scripts/gen_enums.py --fetch` to refresh from the live spec. Each enum "
    "is inlined and repeated across endpoints/content-types in the spec; identical "
    "occurrences are collapsed and values are kept byte-for-byte (upstream escaping "
    "preserved) so the SDK matches what the API accepts."
)

HEADER = '''\
# This file is @generated by scripts/gen_enums.py from openapi/enum-source.json.
# Do not edit by hand — run `python scripts/gen_enums.py` to regenerate.
"""String enums for Blitz API request fields with a fixed set of allowed values.

Every member is a ``str``, so an enum value can be used anywhere a plain string
is accepted and serializes to its exact API value.
"""

from __future__ import annotations

from enum import Enum

__all__ = [
{all_block}]
'''


class Artifact(TypedDict):
    """The committed cache (``openapi/enum-source.json``) shape."""

    _comment: str
    _source_url: str
    spec_version: str
    enums: dict[str, list[str]]


class _Occurrence(NamedTuple):
    values: list[str]
    path: str


def slug(value: str) -> str:
    """Turn an enum value into a valid, upper-snake Python identifier."""
    name = re.sub(r"[^0-9A-Za-z]+", "_", value).strip("_").upper()
    if not name:
        name = "UNKNOWN"
    if name[0].isdigit():
        name = "_" + name
    return name


def member_names(values: list[str]) -> list[tuple[str, str]]:
    """Map each value to a unique member name, disambiguating collisions.

    A disambiguated ``BASE_N`` name can itself collide with a *different* value whose
    slug already is ``BASE_N`` (e.g. values that slug to ``X`` twice plus a value that
    slugs to ``X_2``). Checking only a per-base counter would then emit two identical
    member names, which makes the generated ``Enum`` raise ``TypeError`` on import. So
    each candidate is checked against every name already assigned and the suffix is
    advanced until it is unique.
    """
    used: set[str] = set()
    out: list[tuple[str, str]] = []
    for value in values:
        base = slug(value)
        name = base
        suffix = 2
        while name in used:
            name = f"{base}_{suffix}"
            suffix += 1
        used.add(name)
        out.append((name, value))
    return out


def dedupe_values(values: list[str]) -> list[str]:
    """Drop exact-duplicate values, preserving first-seen order. Keeps near-duplicates."""
    return list(dict.fromkeys(values))


def owning_property(path: list[str]) -> str | None:
    """The nearest ancestor property key that isn't a structural keyword."""
    for key in reversed(path):
        if key not in STRUCTURAL:
            return key
    return None


def extract_enums(spec: object) -> dict[str, list[str]]:
    """Walk an OpenAPI spec and collect the mapped enum value lists.

    Returns the lists keyed by class name in canonical (``PROPERTY_TO_CLASS``)
    order. Identical duplicate occurrences collapse; divergent ones, or a mapped
    property missing from the spec, raise (a human should look). Unmapped enums
    are warned about and skipped.
    """
    found: dict[str, _Occurrence] = {}
    seen: set[int] = set()

    def walk(node: object, path: list[str]) -> None:
        if not isinstance(node, (dict, list)):
            return
        if id(node) in seen:
            return
        seen.add(id(node))

        if isinstance(node, list):
            for item in node:
                walk(item, path)
            return

        obj = cast(dict[str, object], node)
        enum_val = obj.get("enum")
        if (
            isinstance(enum_val, list)
            and obj.get("type") == "string"
            and all(isinstance(v, str) for v in enum_val)
        ):
            owner = owning_property(path)
            json_path = ".".join(path)
            class_name = PROPERTY_TO_CLASS.get(owner) if owner is not None else None
            if class_name is not None:
                values = dedupe_values([v for v in enum_val if isinstance(v, str)])
                prev = found.get(class_name)
                if prev is None:
                    found[class_name] = _Occurrence(values=values, path=json_path)
                elif prev.values != values:
                    raise ValueError(
                        f'Enum "{class_name}" has divergent definitions in the spec:\n'
                        f"  {prev.path} ({len(prev.values)} values)\n"
                        f"  {json_path} ({len(values)} values)\n"
                        "Every occurrence of an enum is expected to be identical. An "
                        "upstream restructure needs a human decision — inspect the spec."
                    )
            elif owner is not None:
                print(
                    f'[gen_enums] Ignoring unmapped enum at "{json_path}" '
                    f'(owning property "{owner}", {len(enum_val)} values). '
                    "Add it to PROPERTY_TO_CLASS if it should be generated.",
                    file=sys.stderr,
                )

        for key, value in obj.items():
            walk(value, [*path, key])

    walk(spec, [])

    missing = [name for name in PROPERTY_TO_CLASS.values() if name not in found]
    if missing:
        raise ValueError(
            f"Spec is missing expected enum(s): {', '.join(missing)}. "
            "A mapped request property was renamed or removed upstream — refusing to "
            "regenerate and silently drop an enum."
        )

    return {name: found[name].values for name in PROPERTY_TO_CLASS.values()}


def build_artifact(spec: object) -> Artifact:
    """Assemble the committed cache (``enum-source.json``) from a fetched spec."""
    enums = extract_enums(spec)
    version = "unknown"
    if isinstance(spec, dict):
        info = spec.get("info")
        if isinstance(info, dict):
            raw = info.get("version")
            if isinstance(raw, str):
                version = raw
    return Artifact(
        _comment=_CACHE_COMMENT,
        _source_url=SPEC_URL,
        spec_version=version,
        enums=enums,
    )


def serialize_artifact(artifact: Artifact) -> str:
    """Serialize the cache: 2-space meta keys, 4-space enum keys, one compact line each.

    Value lists stay on a single line (``industry`` has hundreds of entries) with no
    spaces after commas, so the ``enums`` payload diff is empty when only metadata changes.
    """
    meta_lines = [
        f'  "_comment": {json.dumps(artifact["_comment"], ensure_ascii=False)}',
        f'  "_source_url": {json.dumps(artifact["_source_url"], ensure_ascii=False)}',
        f'  "spec_version": {json.dumps(artifact["spec_version"], ensure_ascii=False)}',
    ]
    enum_lines = [
        f"    {json.dumps(name)}: {json.dumps(values, ensure_ascii=False, separators=(',', ':'))}"
        for name, values in artifact["enums"].items()
    ]
    return (
        "{\n" + ",\n".join(meta_lines) + ',\n  "enums": {\n' + ",\n".join(enum_lines) + "\n  }\n}\n"
    )


def fetch_spec(url: str) -> object:
    """Fetch + parse the OpenAPI spec, with a timeout and a small retry."""
    last_error: Exception | None = None
    for attempt in range(1, FETCH_ATTEMPTS + 1):
        try:
            response = httpx.get(
                url, headers={"accept": "application/json"}, timeout=FETCH_TIMEOUT_S
            )
            response.raise_for_status()
            try:
                parsed: object = json.loads(response.text)
            except json.JSONDecodeError as err:
                raise RuntimeError(f"spec response was not valid JSON: {err}") from err
            return parsed
        except (httpx.HTTPError, RuntimeError) as err:
            last_error = err
            if attempt < FETCH_ATTEMPTS:
                backoff = 0.5 * attempt
                print(
                    f"[gen_enums] fetch attempt {attempt} failed ({err}); "
                    f"retrying in {backoff:.1f}s...",
                    file=sys.stderr,
                )
                time.sleep(backoff)
    raise RuntimeError(
        f"Could not fetch the OpenAPI spec from {url} after {FETCH_ATTEMPTS} attempts: "
        f"{last_error}. Run `python scripts/gen_enums.py --fetch` again when online — "
        "CI does not need the network (`python scripts/gen_enums.py --check` reads the "
        "committed cache)."
    )


def render() -> str:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    enums: dict[str, list[str]] = data["enums"]

    all_block = "".join(f'    "{name}",\n' for name in enums)
    parts = [HEADER.format(all_block=all_block)]

    for class_name, values in enums.items():
        parts.append(f"\n\nclass {class_name}(str, Enum):")
        members = member_names(values)
        if not members:
            parts.append("\n    pass")
            continue
        for member, value in members:
            parts.append(f"\n    {member} = {value!r}")
        parts.append("\n")

    return "".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--fetch",
        action="store_true",
        help="Pull the live OpenAPI spec, then rewrite enum-source.json AND enums.py.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify enums.py is up to date instead of writing it (offline).",
    )
    args = parser.parse_args()

    if args.fetch:
        spec = fetch_spec(SPEC_URL)
        artifact = build_artifact(spec)
        SOURCE.write_text(serialize_artifact(artifact), encoding="utf-8")
        print(
            f"Fetched spec from {SPEC_URL} (version {artifact['spec_version']}); "
            f"wrote {SOURCE.relative_to(ROOT)} ({len(artifact['enums'])} enums)."
        )

    rendered = render()

    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != rendered:
            print(
                "enums.py is out of date. Run `python scripts/gen_enums.py` and commit.",
                file=sys.stderr,
            )
            return 1
        print("enums.py is up to date.")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(rendered, encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(ROOT)} ({len(rendered.splitlines())} lines).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
