#!/usr/bin/env python3
"""Generate the synchronous client + resources from their async sources.

The async code is the single source of truth:

  * ``src/blitz_api/_client_async.py``            -> ``src/blitz_api/_client_sync.py``
  * ``src/blitz_api/resources/_async/<g>.py``     -> ``src/blitz_api/resources/_sync/<g>.py``

Each sync file is produced by transliterating its async source: strip ``async``/``await``
and apply token-level renames (``AsyncBlitzAPI`` -> ``BlitzAPI`` etc.). This is the
"unasync" technique used by httpx and urllib3; we apply it directly via ``tokenize-rt``
so the same code path serves both generation and the CI drift check (no temp-dir dance).

Usage::

    python scripts/gen_sync.py            # rewrite the generated sync files
    python scripts/gen_sync.py --check    # exit 1 if any generated file is out of date

CI runs ``--check`` so a stale generated file fails the build (drift guard), exactly like
``scripts/gen_enums.py`` does for the enums.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any

import tokenize_rt

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "blitz_api"

# Whole-token renames. ``async``/``await`` are stripped separately. Names matching
# ``Async<Upper>...`` with no explicit entry fall back to ``Sync<...>`` (so ``AsyncSleep``
# -> ``SyncSleep`` for free); every name that must drop the prefix entirely is listed here.
REPLACEMENTS: dict[str, str] = {
    "AsyncBlitzAPI": "BlitzAPI",
    "AsyncAccountResource": "AccountResource",
    "AsyncSearchResource": "SearchResource",
    "AsyncEnrichmentResource": "EnrichmentResource",
    "AsyncUtilsResource": "UtilsResource",
    "AsyncRateLimiter": "RateLimiter",
    "AsyncClient": "Client",
    "aclose": "close",
    "__aenter__": "__enter__",
    "__aexit__": "__exit__",
    # Pagination. ``AsyncIterator`` and ``__aiter__`` need explicit entries (the
    # ``Async<Upper>`` fallback would otherwise produce ``SyncIterator``); the module
    # token is renamed so generated sync resources import from ``_pagination_sync``.
    "AsyncPaginator": "Paginator",
    "AsyncCursorPage": "CursorPage",
    "AsyncPageNumberPage": "PageNumberPage",
    "AsyncIterator": "Iterator",
    "__aiter__": "__iter__",
    "_pagination_async": "_pagination_sync",
}

#: (async source, generated sync) file pairs, relative to ``src/blitz_api``.
FILE_PAIRS: list[tuple[str, str]] = [
    ("_pagination_async.py", "_pagination_sync.py"),
    ("_client_async.py", "_client_sync.py"),
    ("resources/_async/__init__.py", "resources/_sync/__init__.py"),
    ("resources/_async/account.py", "resources/_sync/account.py"),
    ("resources/_async/search.py", "resources/_sync/search.py"),
    ("resources/_async/enrichment.py", "resources/_sync/enrichment.py"),
    ("resources/_async/utils.py", "resources/_sync/utils.py"),
    ("_rate_limit_async.py", "_rate_limit_sync.py"),
]

#: ``asyncio.<member>`` -> its synchronous replacement. ``asyncio`` can't be a single
#: whole-token rename because its members map to *different* stdlib modules (``sleep`` ->
#: ``time``, ``Lock`` -> ``threading``). A member not listed here raises (a clear failure
#: beats silently emitting a bogus ``time.<member>``). Add entries as the sources grow.
ASYNCIO_ATTRS: dict[str, str] = {
    "sleep": "time.sleep",
    "Lock": "threading.Lock",
}

_GENERATED_HEADER = (
    "# This file is @generated by scripts/gen_sync.py from {source}.\n"
    "# Do not edit by hand — edit the async source and run `python scripts/gen_sync.py`.\n"
)


def _rewrite_asyncio(source_src: str, source_rel: str) -> str:
    """Rewrite ``asyncio.<member>`` access and the ``import asyncio`` line for the sync twin.

    Each attribute access is replaced with its concrete target (e.g. ``asyncio.Lock`` ->
    ``threading.Lock``); then the ``import asyncio`` statement is replaced with imports for
    exactly the modules those targets need, skipping any already imported (e.g. ``time``,
    kept for ``monotonic``). Indentation is preserved, so an inline ``import asyncio`` inside
    a function transliterates correctly too.
    """
    needed: set[str] = set()

    def _attr(match: re.Match[str]) -> str:
        member = match.group(1)
        target = ASYNCIO_ATTRS.get(member)
        if target is None:
            raise SystemExit(
                f"gen_sync: unsupported asyncio.{member} in {source_rel}; "
                "add it to ASYNCIO_ATTRS with its synchronous equivalent."
            )
        needed.add(target.split(".", 1)[0])
        return target

    source_src = re.sub(r"\basyncio\.(\w+)\b", _attr, source_src)
    if not needed:
        return source_src

    already = set(re.findall(r"^import (\w+)$", source_src, flags=re.MULTILINE))

    def _imp(match: re.Match[str]) -> str:
        indent = match.group(1)
        mods = [m for m in sorted(needed) if m not in already]
        return "\n".join(f"{indent}import {m}" for m in mods)

    return re.sub(r"^([ \t]*)import asyncio$", _imp, source_src, flags=re.MULTILINE)


def _rename(name: str) -> str:
    if name in REPLACEMENTS:
        return REPLACEMENTS[name]
    if len(name) > 5 and name.startswith("Async") and name[5].isupper():
        return "Sync" + name[5:]
    return name


def _transform(source_src: str, source_rel: str) -> str:
    """Return the synchronous transliteration of an async source string."""
    source_src = _rewrite_asyncio(source_src, source_rel)
    tokens = tokenize_rt.src_to_tokens(source_src)
    out: list[Any] = []
    skip_next = False
    for token in tokens:
        if skip_next:
            skip_next = False
            # Drop only the single whitespace token after ``async``/``await`` so
            # ``return await x`` becomes ``return x`` (not ``return  x``). If the keyword
            # was NOT followed by whitespace (e.g. ``await(x)``), keep this token —
            # swallowing it would corrupt the source into ``(x)`` -> ``x)``.
            if token.name == "UNIMPORTANT_WS":
                continue
        if token.src in ("async", "await") and token.name == "NAME":
            skip_next = True
            continue
        if token.name == "NAME":
            token = token._replace(src=_rename(token.src))
        out.append(token)
    body: str = tokenize_rt.tokens_to_src(out)
    return _GENERATED_HEADER.format(source=f"src/blitz_api/{source_rel}") + body


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the generated sync files are up to date instead of writing them.",
    )
    args = parser.parse_args()

    stale: list[str] = []
    for source_rel, target_rel in FILE_PAIRS:
        source_path = SRC / source_rel
        target_path = SRC / target_rel
        rendered = _transform(source_path.read_text(encoding="utf-8"), source_rel)

        if args.check:
            current = target_path.read_text(encoding="utf-8") if target_path.exists() else ""
            if current != rendered:
                stale.append(target_rel)
            continue

        target_path.parent.mkdir(parents=True, exist_ok=True)
        target_path.write_text(rendered, encoding="utf-8")
        print(f"Wrote src/blitz_api/{target_rel}")

    if args.check:
        if stale:
            print(
                "Generated sync files are out of date: "
                + ", ".join(stale)
                + "\nRun `python scripts/gen_sync.py` and commit.",
                file=sys.stderr,
            )
            return 1
        print("Generated sync files are up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
