# This file is @generated by scripts/gen_sync.py from src/blitz_api/_client_async.py.
# Do not edit by hand — edit the async source and run `python scripts/gen_sync.py`.
"""The Blitz API client implementation (async source; sync is generated alongside)."""

from __future__ import annotations

from functools import cached_property
from types import TracebackType
from typing import Any

import httpx

from . import _constants as C
from ._base_client import BaseClient, ResponseT, to_jsonable
from ._compat import SyncSleep, TimeoutParam
from ._exceptions import APIConnectionError, APITimeoutError
from ._pagination_base import BasePage
from ._rate_limit import RateLimiter
from .resources import (
    AccountResource,
    EnrichmentResource,
    SearchResource,
    UtilsResource,
)


class BlitzAPI(BaseClient):
    """Client for the Blitz API.

    ``AsyncBlitzAPI`` is the async client and ``BlitzAPI`` is the sync client; both
    expose an identical method surface. See the ``blitz_api`` package docstring for a
    quickstart. (This docstring is shared with the generated sync client, so it stays
    flavour-neutral.)
    """

    def __init__(
        self,
        api_key: str | None = None,
        *,
        base_url: str = C.DEFAULT_BASE_URL,
        timeout: float | httpx.Timeout = C.DEFAULT_TIMEOUT,
        max_retries: int = C.DEFAULT_MAX_RETRIES,
        rate_limit_rps: float | None = C.DEFAULT_RATE_LIMIT_RPS,
        http_client: httpx.Client | None = None,
        sleep: SyncSleep | None = None,
    ) -> None:
        super().__init__(api_key=api_key, base_url=base_url, max_retries=max_retries)
        if http_client is not None and timeout != C.DEFAULT_TIMEOUT:
            raise ValueError(
                "Pass `timeout` or `http_client`, not both: a supplied http_client carries "
                "its own timeout. Set the timeout on your httpx client instead."
            )
        self._http_client = http_client or httpx.Client(timeout=timeout)
        self._owns_http_client = http_client is None
        self._rate_limit_rps = rate_limit_rps
        # One limiter per endpoint path so each endpoint's rate limit is tracked
        # independently (e.g. ``.email`` and ``.phone`` do not share a budget). Built
        # lazily in ``_limiter_for`` on first use of each path.
        self._rate_limiters: dict[str, RateLimiter] = {}
        if sleep is None:
            import time

            sleep = time.sleep
        self._sleep = sleep

    def _limiter_for(self, path: str) -> RateLimiter:
        """Return the per-endpoint limiter for ``path``, creating it on first use.

        Each endpoint path gets its own sliding window so its rate limit is tracked
        independently of every other endpoint.
        """
        limiter = self._rate_limiters.get(path)
        if limiter is None:
            # ``setdefault`` keeps concurrent first-callers on the same instance; any
            # extra limiter built in a race is harmlessly discarded. Thread the client's
            # ``sleep`` through so a custom/fake sleep injected for tests also drives the
            # limiter's throttle wait, not just the retry backoff.
            limiter = self._rate_limiters.setdefault(
                path, RateLimiter(self._rate_limit_rps, sleep=self._sleep)
            )
        return limiter

    def _request(
        self,
        method: str,
        path: str,
        *,
        body: Any | None,
        cast_to: type[ResponseT],
        timeout: TimeoutParam = None,
    ) -> ResponseT:
        url = self._build_url(path)
        headers = self._build_headers()
        json_body = to_jsonable(body) if body is not None else None

        attempt = 0
        while True:
            self._limiter_for(path).acquire()
            try:
                if timeout is None:
                    response = self._http_client.request(
                        method, url, headers=headers, json=json_body
                    )
                else:
                    response = self._http_client.request(
                        method, url, headers=headers, json=json_body, timeout=timeout
                    )
            except httpx.TimeoutException as exc:
                if self._should_retry_exception(exc) and attempt < self.max_retries:
                    attempt += 1
                    self._sleep(self._backoff_seconds(attempt))
                    continue
                raise APITimeoutError(request=exc.request) from exc
            except httpx.RequestError as exc:
                if self._should_retry_exception(exc) and attempt < self.max_retries:
                    attempt += 1
                    self._sleep(self._backoff_seconds(attempt))
                    continue
                raise APIConnectionError(
                    str(exc) or "Connection error.", request=exc.request
                ) from exc

            if response.is_success:
                result = self._parse_model(response, cast_to)
                if isinstance(result, BasePage):
                    result._bind(self, method, path, json_body, timeout)
                return result

            if self._should_retry(response.status_code) and attempt < self.max_retries:
                attempt += 1
                self._sleep(self._retry_delay(response, attempt))
                continue

            raise self._make_status_error(response)

    def close(self) -> None:
        """Close the underlying HTTP connection pool (if owned by this client)."""
        if self._owns_http_client:
            self._http_client.close()

    def __enter__(self) -> BlitzAPI:
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None:
        self.close()

    @cached_property
    def account(self) -> AccountResource:
        return AccountResource(self)

    @cached_property
    def search(self) -> SearchResource:
        return SearchResource(self)

    @cached_property
    def enrichment(self) -> EnrichmentResource:
        return EnrichmentResource(self)

    @cached_property
    def utils(self) -> UtilsResource:
        return UtilsResource(self)
