# This file is @generated by scripts/gen_sync.py from src/blitz_api/resources/_async/__init__.py.
# Do not edit by hand — edit the async source and run `python scripts/gen_sync.py`.
"""Blitz API resource classes, grouped by the API's OpenAPI tags."""
