# This file is @generated by scripts/gen_sync.py from src/blitz_api/resources/_async/account.py.
# Do not edit by hand — edit the async source and run `python scripts/gen_sync.py`.
"""The Account resource: ``client.account``."""

from __future__ import annotations

from typing import TYPE_CHECKING

from ..._compat import TimeoutParam
from ...types.account import KeyInfo

if TYPE_CHECKING:
    from ..._client import BlitzAPI

_KEY_INFO_PATH = "/v2/account/key-info"


class AccountResource:
    def __init__(self, client: BlitzAPI) -> None:
        self._client = client

    def key_info(self, *, timeout: TimeoutParam = None) -> KeyInfo:
        """Check the API key's validity, credit balance, and rate limit.

        A cheap health check to run before a batch job.
        """
        return self._client._request(
            "GET", _KEY_INFO_PATH, body=None, cast_to=KeyInfo, timeout=timeout
        )
