# This file is @generated by scripts/gen_sync.py from src/blitz_api/resources/_async/changelog.py.
# Do not edit by hand — edit the async source and run `python scripts/gen_sync.py`.
"""The Changelog resource: ``client.changelog``."""

from __future__ import annotations

from typing import TYPE_CHECKING

from ..._compat import TimeoutParam
from ...types.changelog import ChangelogEntry, ChangelogResponse

if TYPE_CHECKING:
    from ..._client import BlitzAPI

# Public endpoint: NO ``/v2`` prefix, and the trailing slash is load-bearing.
_CHANGELOG = "/changelog/"


class ChangelogResource:
    def __init__(self, client: BlitzAPI) -> None:
        self._client = client

    def list(
        self,
        *,
        days: int | None = None,
        limit: int | None = None,
        timeout: TimeoutParam = None,
    ) -> list[ChangelogEntry]:
        """List the public Blitz API changelog, newest-first.

        Each entry carries a ``date``, a ``type`` (``breaking`` | ``feature`` |
        ``improvement`` | ``fix`` | ``deprecation`` | ``announcement``), a ``title``, and
        optional ``body``, ``affected_endpoints``, and ``links``.

        This endpoint is **public** — it costs no records and works regardless of API-key
        validity (the SDK still sends the key header, which the endpoint ignores). It is
        **not paginated**: it returns a plain list filtered by the ``days`` / ``limit``
        query parameters.
        """
        params = {"days": days, "limit": limit}
        result = self._client._request(
            "GET",
            _CHANGELOG,
            body=None,
            cast_to=ChangelogResponse,
            params=params,
            timeout=timeout,
        )
        return result.root
