# This file is @generated by scripts/gen_sync.py from src/blitz_api/resources/_async/search.py.
# Do not edit by hand — edit the async source and run `python scripts/gen_sync.py`.
"""The Search resource: ``client.search``."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from ..._compat import TimeoutParam
from ..._pagination_sync import CursorPage, PageNumberPage
from ...types.filters import (
    CascadeTier,
    CompanyFilter,
    ContinentValue,
    JobFunctionValue,
    JobLevelValue,
    PeopleFilter,
    SalesRegionValue,
)
from ...types.search import WaterfallIcpResponse
from ...types.shared import Company, Person

if TYPE_CHECKING:
    from ..._client import BlitzAPI

_PEOPLE = "/v2/search/people"
_COMPANIES = "/v2/search/companies"
_EMPLOYEE_FINDER = "/v2/search/employee-finder"
_WATERFALL = "/v2/search/waterfall-icp-keyword"


def _drop_none(**kwargs: Any) -> dict[str, Any]:
    """Build a request body keeping only the arguments the caller provided."""
    return {key: value for key, value in kwargs.items() if value is not None}


def _employee_finder_body(
    *,
    company_linkedin_url: str,
    country_code: list[str] | None,
    continent: list[ContinentValue] | None,
    sales_region: list[SalesRegionValue] | None,
    job_level: list[JobLevelValue] | None,
    job_function: list[JobFunctionValue] | None,
    min_connections_count: int | None,
    max_results: int | None,
    page: int | None,
) -> dict[str, Any]:
    return _drop_none(
        company_linkedin_url=company_linkedin_url,
        country_code=country_code,
        continent=continent,
        sales_region=sales_region,
        job_level=job_level,
        job_function=job_function,
        min_connections_count=min_connections_count,
        max_results=max_results,
        page=page,
    )


class SearchResource:
    def __init__(self, client: BlitzAPI) -> None:
        self._client = client

    def people(
        self,
        *,
        company: CompanyFilter | None = None,
        people: PeopleFilter | None = None,
        max_results: int | None = None,
        cursor: str | None = None,
        timeout: TimeoutParam = None,
    ) -> CursorPage[Person]:
        """Search people across many companies, combining company and persona filters.

        Auto-paginates over every matching person when the result is iterated; use
        ``.iter_pages()`` or the ``cursor=`` arg for manual control.
        """
        body = _drop_none(company=company, people=people, max_results=max_results, cursor=cursor)
        return self._client._request(
            "POST", _PEOPLE, body=body, cast_to=CursorPage[Person], timeout=timeout
        )

    def companies(
        self,
        *,
        company: CompanyFilter | None = None,
        max_results: int | None = None,
        cursor: str | None = None,
        timeout: TimeoutParam = None,
    ) -> CursorPage[Company]:
        """Find companies matching ICP filters (industry, size, HQ, revenue, ...).

        Auto-paginates over every matching company; use ``.iter_pages()`` or ``cursor=``
        for manual control.
        """
        body = _drop_none(company=company, max_results=max_results, cursor=cursor)
        return self._client._request(
            "POST", _COMPANIES, body=body, cast_to=CursorPage[Company], timeout=timeout
        )

    def employee_finder(
        self,
        *,
        company_linkedin_url: str,
        country_code: list[str] | None = None,
        continent: list[ContinentValue] | None = None,
        sales_region: list[SalesRegionValue] | None = None,
        job_level: list[JobLevelValue] | None = None,
        job_function: list[JobFunctionValue] | None = None,
        min_connections_count: int | None = None,
        max_results: int | None = None,
        page: int | None = None,
        timeout: TimeoutParam = None,
    ) -> PageNumberPage[Person]:
        """Search employees at a single company, with page-based pagination.

        Auto-paginates over every matching employee; use ``.iter_pages()`` or ``page=``
        for manual control.
        """
        body = _employee_finder_body(
            company_linkedin_url=company_linkedin_url,
            country_code=country_code,
            continent=continent,
            sales_region=sales_region,
            job_level=job_level,
            job_function=job_function,
            min_connections_count=min_connections_count,
            max_results=max_results,
            page=page,
        )
        return self._client._request(
            "POST",
            _EMPLOYEE_FINDER,
            body=body,
            cast_to=PageNumberPage[Person],
            timeout=timeout,
        )

    def waterfall_icp(
        self,
        *,
        company_linkedin_url: str,
        cascade: list[CascadeTier],
        max_results: int | None = None,
        timeout: TimeoutParam = None,
    ) -> WaterfallIcpResponse:
        """Find the best decision-maker at a company via a prioritized cascade."""
        body = _drop_none(
            company_linkedin_url=company_linkedin_url, cascade=cascade, max_results=max_results
        )
        return self._client._request(
            "POST", _WATERFALL, body=body, cast_to=WaterfallIcpResponse, timeout=timeout
        )
