# This file is @generated by scripts/gen_sync.py from src/blitz_api/resources/_async/utils.py.
# Do not edit by hand — edit the async source and run `python scripts/gen_sync.py`.
"""The Utilities resource: ``client.utils``."""

from __future__ import annotations

from typing import TYPE_CHECKING

from ..._compat import TimeoutParam
from ...types.utils import (
    CompanyDepartmentDistributionResponse,
    CompanyEmploymentDistributionResponse,
    CurrentDateResponse,
)

if TYPE_CHECKING:
    from ..._client import BlitzAPI

_CURRENT_DATE = "/v2/utils/current-date"
_EMPLOYMENT_DISTRIBUTION = "/v2/utils/company-employment-distribution"
_DEPARTMENT_DISTRIBUTION = "/v2/utils/company-department-distribution"


class UtilsResource:
    def __init__(self, client: BlitzAPI) -> None:
        self._client = client

    def current_date(
        self, *, region: str, timeout: TimeoutParam = None
    ) -> CurrentDateResponse:
        """Get the current server date/time for an IANA timezone (e.g. ``America/New_York``)."""
        return self._client._request(
            "POST",
            _CURRENT_DATE,
            body={"region": region},
            cast_to=CurrentDateResponse,
            timeout=timeout,
        )

    def company_employment_distribution(
        self, *, company_linkedin_url: str, timeout: TimeoutParam = None
    ) -> CompanyEmploymentDistributionResponse:
        """Get a company's employee count broken down by country."""
        return self._client._request(
            "POST",
            _EMPLOYMENT_DISTRIBUTION,
            body={"company_linkedin_url": company_linkedin_url},
            cast_to=CompanyEmploymentDistributionResponse,
            timeout=timeout,
        )

    def company_department_distribution(
        self, *, company_linkedin_url: str, timeout: TimeoutParam = None
    ) -> CompanyDepartmentDistributionResponse:
        """Get a company's employee count broken down by department.

        Employees with no classified department are counted under ``"Other"``.
        """
        return self._client._request(
            "POST",
            _DEPARTMENT_DISTRIBUTION,
            body={"company_linkedin_url": company_linkedin_url},
            cast_to=CompanyDepartmentDistributionResponse,
            timeout=timeout,
        )
